// Code generated by protoc-gen-go. DO NOT EDIT.
// source: UserModel.proto

package models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserModel struct {
	UserId               int32    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Score                int32    `protobuf:"varint,3,opt,name=Score,proto3" json:"Score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserModel) Reset()         { *m = UserModel{} }
func (m *UserModel) String() string { return proto.CompactTextString(m) }
func (*UserModel) ProtoMessage()    {}
func (*UserModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_4850c778bbe5c1d8, []int{0}
}

func (m *UserModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserModel.Unmarshal(m, b)
}
func (m *UserModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserModel.Marshal(b, m, deterministic)
}
func (m *UserModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserModel.Merge(m, src)
}
func (m *UserModel) XXX_Size() int {
	return xxx_messageInfo_UserModel.Size(m)
}
func (m *UserModel) XXX_DiscardUnknown() {
	xxx_messageInfo_UserModel.DiscardUnknown(m)
}

var xxx_messageInfo_UserModel proto.InternalMessageInfo

func (m *UserModel) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserModel) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserModel) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func init() {
	proto.RegisterType((*UserModel)(nil), "UserModel")
}

func init() { proto.RegisterFile("UserModel.proto", fileDescriptor_4850c778bbe5c1d8) }

var fileDescriptor_4850c778bbe5c1d8 = []byte{
	// 112 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x0f, 0x2d, 0x4e, 0x2d,
	0xf2, 0xcd, 0x4f, 0x49, 0xcd, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x0a, 0xe5, 0xe2, 0x84,
	0x0b, 0x09, 0x89, 0x71, 0xb1, 0x81, 0x38, 0x9e, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xac, 0x41,
	0x50, 0x9e, 0x90, 0x14, 0x17, 0x07, 0x88, 0xe5, 0x97, 0x98, 0x9b, 0x2a, 0xc1, 0xa4, 0xc0, 0xa8,
	0xc1, 0x19, 0x04, 0xe7, 0x0b, 0x89, 0x70, 0xb1, 0x06, 0x27, 0xe7, 0x17, 0xa5, 0x4a, 0x30, 0x83,
	0xb5, 0x40, 0x38, 0x4e, 0x5c, 0x51, 0x1c, 0x7a, 0xd6, 0xb9, 0x20, 0x43, 0x8b, 0x93, 0xd8, 0xc0,
	0x36, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x53, 0x4d, 0x84, 0x93, 0x7c, 0x00, 0x00, 0x00,
}
